# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'terraform_install'
    displayName: 'Install Terraform'
    jobs:
      - job: 'terraform_install'
        displayName: 'Install Terraform'
        steps:
          - checkout: none
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.24'
  - stage: 'terraform_plan'
    displayName: 'Plan Terraform'
    jobs:
      - job: terraform_plan
        displayName: 'Init and Plan Terraform'
        steps:
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
              backendAzureRmResourceGroupName: 'rg-par-storage-shared-002'
              backendAzureRmStorageAccountName: 'stparaksshared003'
              backendAzureRmContainerName: 'tfstate-aks'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=tfplan'
              environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
          - publish: tfplan
            artifact: tfplan
            displayName: Publish Terraform Plan
          # - task: TerraformTaskV1@0
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'apply'
          #     commandOptions: '-auto-approve terraform.tfplan'
          #     environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'