# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'terraform_install'
    displayName: 'Install Terraform'
    jobs:
      - job: 'terraform_install'
        displayName: 'Install Terraform'
        steps:
          - checkout: none
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.24'
  - stage: 'terraform_plan'
    displayName: 'Plan Terraform'
    jobs:
      - job: terraform_plan
        displayName: 'Init and Plan Terraform'
        steps:
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
              backendAzureRmResourceGroupName: 'rg-par-storage-shared-002'
              backendAzureRmStorageAccountName: 'stparaksshared003'
              backendAzureRmContainerName: 'tfstate-aks'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=tfplan'
              environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
          - publish: ./
            artifact: terraform-artifacts
            displayName: Publish Terraform Artifacts
  - stage: 'terraform_apply'
    displayName: 'Apply Terraform'
    jobs:
      - job: terraform_apply
        displayName: 'Apply Terraform'
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            displayName: Retrieve Terraform Artifacts
            inputs:
              artifact: terraform-artifacts
              path: $(Build.SourcesDirectory)
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve tfplan'
              environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'