trigger: none
pr: none
  
pool:
  vmImage: 'ubuntu-18.04'

parameters:
- name: 'isDestroy'
  displayName: 'Destroy operation'
  type: boolean
  default: false

stages:
  - stage: 'terraform_plan'
    displayName: 'Plan Terraform'
    jobs:
      - job: terraform_plan
        displayName: 'Plan Terraform'
        steps:
          - bash: |
              [ -z "$(backendAzureRmSubscriptionId)" ] && echo 'Variable "backendAzureRmSubscriptionId" is not set' && exit 1
              [ -z "$(backendAzureRmTenantId)" ] && echo 'Variable "backendAzureRmTenantId" is not set' && exit 1
              [ -z "$(backendAzureRmClientId)" ] && echo 'Variable "backendAzureRmClientId" is not set' && exit 1
              [ -z "$(backendAzureRmClientSecret)" ] && echo 'Variable "backendAzureRmClientSecret" is not set' && exit 1
              [ -z "$(backendAzureRmResourceGroupName)" ] && echo 'Variable "backendAzureRmResourceGroupName" is not set' && exit 1
              [ -z "$(backendAzureRmStorageAccountName)" ] && echo 'Variable "backendAzureRmStorageAccountName" is not set' && exit 1
              [ -z "$(backendAzureRmContainerName)" ] && echo 'Variable "backendAzureRmContainerName" is not set' && exit 1
              [ -z "$(backendAzureRmKey)" ] && echo 'Variable "backendAzureRmKey" is not set' && exit 1
              [ -z "$(subscriptionId)" ] && echo 'Variable "subscriptionId" is not set' && exit 1
              [ -z "$(tenantId)" ] && echo 'Variable "tenantId" is not set' && exit 1
              [ -z "$(servicePrincipleId)" ] && echo 'Variable "servicePrincipleId" is not set' && exit 1
              [ -z "$(servicePrincipleSecret)" ] && echo 'Variable "servicePrincipleSecret" is not set' && exit 1
              [ -z "$(aksResourceGroupName)" ] && echo 'Variable "aksResourceGroupName" is not set' && exit 1
              [ -z "$(aksLocation)" ] && echo 'Variable "aksLocation" is not set' && exit 1
              [ -z "$(aksClusterName)" ] && echo 'Variable "aksClusterName" is not set' && exit 1
              [ -z "$(aksAdminGroupID)" ] && echo 'Variable "aksAdminGroupID" is not set' && exit 1
              [ -z "$(clusterIssuerContactEmail)" ] && echo 'Variable "clusterIssuerContactEmail" is not set' && exit 1
              [ -z "$(aksNodeSize)" ] && echo 'Variable "aksNodeSize" is not set' && exit 1
              [ -z "$(aksNodeCount)" ] && echo 'Variable "aksNodeCount" is not set' && exit 1
              [ -z "$(kubeVersion)" ] && echo 'Variable "kubeVersion" is not set' && exit 1
              [ -z '$(resourceTags)' ] && echo 'Variable "resourceTags" is not set' && exit 1

              echo 'All variables are set'
            displayName: 'Check Pipeline Variables'
            name: 'check_variables'
          - checkout: self
          - task: Bash@3
            displayName: 'Check tool version'
            inputs:
              targetType: 'inline'
              script: |
                terraform version
                helm version
          - bash: |
              set -ex
              terraform init \
                  -backend-config=storage_account_name=$(backendAzureRmStorageAccountName) \
                  -backend-config=container_name=$(backendAzureRmContainerName) \
                  -backend-config=key=$(backendAzureRmKey) \
                  -backend-config=resource_group_name=$(backendAzureRmResourceGroupName) \
                  -backend-config=subscription_id=$(backendAzureRmSubscriptionId) \
                  -backend-config=tenant_id=$(backendAzureRmTenantId) \
                  -backend-config=client_id=$(backendAzureRmClientId) \
                  -backend-config=client_secret=$(backendAzureRmClientSecret)
            displayName: 'Init Terraform'
            name: 'init_terraform'
          - bash: |
              set -ex
              terraform providers
              terraform plan -out=tfplan $DESTROY \
                  -var subscription_id=$(subscriptionId) \
                  -var tenant_id=$(tenantId) \
                  -var client_id=$(servicePrincipleId) \
                  -var client_secret=$(servicePrincipleSecret) \
                  -var resource_group_name=$(aksResourceGroupName) \
                  -var location=$(aksLocation) \
                  -var aks_cluster_name=$(aksClusterName) \
                  -var aks_node_size=$(aksNodeSize) \
                  -var aks_node_count=$(aksNodeCount) \
                  -var kubernetes_version=$(kubeVersion) \
                  -var admin_group_id=$(aksAdminGroupID) \
                  -var cluster_issuer_email=$(clusterIssuerContactEmail) \
                  -var tags='$(resourceTags)'
            displayName: 'Plan Terraform'
            name: 'plan_terraform'
            ${{ if eq(parameters.isDestroy, true) }}:
              env:
                DESTROY: '--destroy'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'terraform'
              publishLocation: 'pipeline'
  - stage: 'terraform_apply'
    displayName: 'Apply Terraform'
    jobs:
      - deployment: apply_terraform
        displayName: 'Apply Terraform'
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - bash: |
                    set -ex
                    cd $(Pipeline.Workspace)/terraform
                    chmod -R +x .terraform/providers
                    helm repo add stable https://charts.helm.sh/stable
                    helm repo add jetstack https://charts.jetstack.io
                    helm repo add pacroy https://pacroy.github.io/helm-repo/
                    helm repo update
                    terraform providers
                    terraform apply -auto-approve tfplan
                  displayName: 'Apply Terraform'
                  name: 'apply_terraform'
