# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'terraform_apply'
    displayName: 'Apply Terraform'
    jobs:
      - job: 'terraform_install'
        displayName: 'Install Terraform'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.24'
      - job: terraform_init
        displayName: 'Init Terraform'
        dependsOn: 'terraform_install'
        steps:
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
              backendAzureRmResourceGroupName: 'rg-par-storage-shared-002'
              backendAzureRmStorageAccountName: 'stparaksshared003'
              backendAzureRmContainerName: 'tfstate-aks'
              backendAzureRmKey: 'tf/terraform.tfstate'
      - job: terraform_plan
        displayName: 'Plan Terraform'
        dependsOn: 'terraform_init'
        steps:
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=terraform.tfplan'
              environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'
      - job: terrafrom_apply
        displayName: 'Apply Terraform'
        dependsOn: 'terraform_plan'
        steps:
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve terraform.tfplan'
              environmentServiceNameAzureRM: 'par-shared-002(99813d40-928b-44b2-a969-2c7ea5bd8b96)'